### ISSUE TITLE
Controllers/EventController/Details

### ISSUE THREAD

**Issue by aOverholt** [Macks1776/RSI-Calendar#113]

**Comment by Macks1776** [comment]
So I got this made, but it is ugly. It's functional but lacking the proper CSS. Right now it is in the Max 2 branch. Using that branch will require updating the database because I forgot to add a field for description when I first made the Events table. I also deleted some unnecessary fields from the Events table since we are storing StartDate and EndDate as DateTime types instead of separate strings for date and time.
